version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name final-work-codedeploy --s3-location s3://final-work-ope/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src